---
title: "Data Manipulation"
output: git_document
---

```{r setup and read in data}
library(tidyverse)
options(tibble.print_min = 3)

litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

**Select** function in dplyr package 
#select only a subset of the whole data set
```{r selected columns}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)

select(litters_df, group:gd_of_birth)

select(litters_df, starts_with("gd"))
```

```{r remove columns }
select(litters_df, -pups_survive)
select(litters_df, -group:gd_of_birth)
```

```{r rename variables}
select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r relocate variables}
select(litters_df, litter_number, everything())
```

**filter** function 
#_filter_ rows based on my statement while _select_ keeps every rows
```{r logical operator}
filter(litters_df,gd0_weight < 22)
filter(litters_df, gd_of_birth == 20)
```

```{r flip the state}
filter(litters_df, !(gd_of_birth == 20))
filter(litters_df, gd_of_birth != 20)
```

```{r multiple logics}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r keep selected rows }
filter(litters_df, group == "Con7")
filter(litters_df,group == "Con8" )
filter(litters_df, group %in% c("Con8", "Con7" ))
```


**mutate** function 
#creating new variables or modifying existing one
```{r add variables with existing one and modifies the group variable }
mutate(litters_df,wt_gain = gd18_weight - gd0_weight, group = str_to_lower(group))
```


**arrange** function
#put data in order
```{r arrange by variables}
arrange(litters_df,pups_born_alive)
arrange(litters_df, pups_born_alive, gd0_weight)
```


##pipes **%>%
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
```