---
title: "tidy data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Pivot_longer 
load the PULSE data
```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% janitor::clean_names()
```

Is the tidy here same as rbind()?
Wide format to long format
```{r }
pulse_data_tidy = pulse_data %>% pivot_longer(bdi_score_bl:bdi_score_12m, names_to = "visit", names_prefix = "bdi_score_", values_to = "bdi")
```

rewrite, combine and extent(to add a mutate)
  stack the bdi score
  formalize the "visit" variable
```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% janitor::clean_names() %>%
  pivot_longer(bdi_score_bl:bdi_score_12m, names_to = "visit", names_prefix = "bdi_score_", values_to = "bdi") %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))

```

## Pivot_wider 
Make up some data 
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4))

pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```

## Binding rows 
Read in data, keep certain rows, create new variables by movies
```{r}
fellowship_ring = readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

bind all my "mutate" rows together 
```{r}
lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()) 
```


## Joining datasets 
```{r}
```

